In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

In [6]:
df = pd.read_csv('winequality-red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [7]:
df.shape

(1599, 12)

In [8]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [9]:
df['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [10]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [11]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)

(1599, 11)
(1599,)


In [12]:
x.head()

fixed acidity  volatile acidity  citric acid  ...    pH  sulphates  alcohol
0            7.4              0.70         0.00  ...  3.51       0.56      9.4
1            7.8              0.88         0.00  ...  3.20       0.68      9.8
2            7.8              0.76         0.04  ...  3.26       0.65      9.8
3           11.2              0.28         0.56  ...  3.16       0.58      9.8
4            7.4              0.70         0.00  ...  3.51       0.56      9.4

[5 rows x 11 columns]

In [13]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1199, 11)
(400, 11)
(1199,)
(400,)


In [16]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [17]:
y_test.value_counts()

5    178
6    166
7     41
4      8
8      6
3      1
Name: quality, dtype: int64

In [18]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.linear_model import LogisticRegression

Create a function to implement different models

In [21]:
def apply_model(model,x_train,y_train,x_test,y_test):
    m = model
    m.fit(x_train,y_train)
    print('Training score',m.score(x_train,y_train))
    print('Testing score',m.score(x_test,y_test))
    ypred = m.predict(x_test)
    print('y_pred\n',ypred)
    cm = confusion_matrix(y_test,ypred)
    print('Confusion Matrix\n',cm)
    print('Cls Report\n',classification_report(y_test,ypred))

In [22]:
m1 = LogisticRegression(solver='liblinear')
apply_model(m1,x_train,y_train,x_test,y_test)

Training score 0.5863219349457881
Testing score 0.605
y_pred
 [7 6 5 6 5 5 7 5 5 5 5 5 5 6 5 5 6 5 6 6 6 6 7 6 6 5 6 7 5 5 6 5 6 7 6 5 5
 5 5 5 6 6 6 6 5 6 6 5 6 5 6 5 6 5 5 5 5 5 5 5 5 7 5 6 6 6 6 6 7 6 5 6 5 5
 6 6 5 5 5 5 6 6 6 7 5 5 5 6 5 5 5 5 5 5 6 5 5 5 5 7 6 6 6 5 6 6 5 6 5 6 6
 6 5 6 6 5 5 5 5 5 6 6 5 7 5 5 5 6 6 6 6 5 5 5 6 5 6 7 6 6 5 6 6 6 6 7 5 6
 5 5 6 5 5 6 5 6 5 5 6 5 6 6 6 6 6 6 6 5 6 5 5 5 5 5 5 5 6 5 5 5 5 6 5 6 6
 5 5 5 5 6 5 5 6 6 6 5 6 5 5 6 5 5 6 5 5 6 5 5 6 5 6 6 6 5 6 5 5 5 6 6 5 6
 5 5 5 5 6 7 5 5 6 6 6 6 6 6 5 6 6 6 6 5 5 5 5 5 5 6 5 5 5 6 5 6 5 5 5 6 5
 5 5 5 6 6 6 5 6 6 6 5 5 6 5 6 7 6 6 5 5 5 6 5 5 5 5 6 5 6 5 6 6 5 6 5 6 7
 6 5 6 5 5 5 5 5 5 5 6 5 6 5 6 6 6 6 6 6 6 6 5 5 5 6 5 6 6 5 5 6 5 5 7 6 6
 5 6 6 5 5 5 5 5 5 6 5 7 6 5 6 7 7 6 6 6 7 5 6 5 5 6 6 5 7 5 5 6 6 6 6 6 5
 7 5 6 5 6 6 6 6 6 6 6 5 6 7 6 6 6 5 5 6 5 6 5 6 6 6 6 7 6 6]
Confusion Matrix
 [[  0   0   0   1   0   0]
 [  0   0   5   1   2   0]
 [  0   0 134  41   3   0]
 [  0   0  53 102  11   0]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
m2 = RandomForestClassifier(n_estimators = 45,max_depth = 8,min_samples_split = 17)
apply_model(m2,x_train,y_train,x_test,y_test)

Training score 0.79232693911593
Testing score 0.6675
y_pred
 [7 6 5 6 5 5 7 5 5 5 5 5 6 6 6 5 6 5 5 6 6 5 6 6 6 5 7 7 6 5 7 5 6 6 6 5 5
 5 6 5 5 6 5 5 5 6 7 6 6 5 7 5 7 5 6 5 5 6 5 5 5 7 6 7 6 5 6 6 7 6 5 6 5 5
 6 6 5 6 5 5 7 6 6 6 5 5 5 6 5 5 6 5 5 5 6 5 5 5 5 7 6 6 6 6 6 6 5 6 5 5 6
 6 5 6 5 6 5 5 5 5 6 5 5 6 5 6 6 6 6 6 6 5 5 5 7 5 6 7 5 6 5 5 6 7 7 7 5 6
 5 6 6 5 5 6 6 6 5 5 6 5 6 5 6 6 6 6 6 5 6 6 6 5 5 5 5 6 6 5 5 5 5 6 5 6 6
 5 5 6 6 6 5 5 7 7 5 5 6 5 5 6 5 5 6 5 6 6 5 5 6 5 6 6 6 5 6 5 5 5 6 6 5 6
 5 5 5 5 7 7 5 5 5 6 7 6 6 6 5 6 6 6 6 5 6 5 5 6 5 6 5 5 6 6 5 6 6 5 5 6 5
 5 5 5 6 6 6 5 6 6 6 5 6 6 5 6 7 6 6 5 6 5 6 5 6 5 5 6 6 6 6 5 6 5 6 5 6 7
 6 5 6 5 5 5 5 5 5 5 6 5 7 5 6 6 6 6 6 6 5 6 6 5 5 6 5 6 6 5 6 5 6 5 5 6 7
 5 6 6 5 5 5 5 5 5 6 5 7 6 5 6 7 6 6 6 6 7 5 6 6 5 6 7 5 7 5 5 7 6 6 6 6 5
 7 5 6 6 7 6 6 6 6 6 6 5 6 6 5 6 6 5 5 6 5 6 5 6 6 6 6 7 6 6]
Confusion Matrix
 [[  0   0   1   0   0   0]
 [  0   0   4   3   1   0]
 [  0   0 134  40   4   0]
 [  0   0  38 116  12   0]
 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
