In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('titanic_train.csv')
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [8]:
df['Age'].value_counts().sort_values(ascending=False)

24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
66.00     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: Age, Length: 88, dtype: int64

In [9]:
##This is for my reference w.r.t above cell
df['Age'].value_counts()

24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: Age, Length: 88, dtype: int64

In [10]:
df['Age'].mean()

29.69911764705882

In [11]:
##When inplace=True is passed, the data is renamed in place (it returns nothing)
df['Age'].fillna(df['Age'].mean(),inplace=True)
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [12]:
df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [13]:
df['Embarked'].fillna('S', inplace=True)
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [14]:
df['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

The two null values are assigned the value 'S'.

In [15]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

DataFrame.nunique(axis=0, dropna=True)</br>
<b>Count number of distinct elements in specified axis.</b></br>

Return Series with number of distinct elements.</br> Can ignore NaN values.

In [16]:
#Columns to be excluded
print(df['Name'].nunique())
print(df['Ticket'].nunique())

891
681


<b>Correlation Values</b></br>
The values range between -1.0 and 1.0.</br> A correlation of -1.0 shows a perfect negative correlation, while a correlation of 1.0 shows a perfect positive correlation.</br> Negative correlation is a relationship between two variables in which one variable increases as the other decreases, and vice versa.<br/> A perfect negative correlation means the relationship that exists between two variables is exactly opposite all of the time.<br/>

In [17]:
df.corr()['Survived']

PassengerId   -0.005007
Survived       1.000000
Pclass        -0.338481
Age           -0.069809
SibSp         -0.035322
Parch          0.081629
Fare           0.257307
Name: Survived, dtype: float64

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
lb = LabelEncoder()
df['Sex'] = lb.fit_transform(df['Sex'])
df['Embarked'] = lb.fit_transform(df['Embarked'])
df.head(3)

PassengerId  Survived  Pclass  ...     Fare  Cabin  Embarked
0            1         0       3  ...   7.2500    NaN         2
1            2         1       1  ...  71.2833    C85         0
2            3         1       3  ...   7.9250    NaN         2

[3 rows x 12 columns]

In [20]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked         int64
dtype: object

### Model 1 </br>
Columns excluded - PassengerId, Name, Ticket, Cabin

In [21]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [22]:
x = df.iloc[:,[2,4,5,6,7,9,11]]
y = df.iloc[:,1]
print(x.shape,y.shape)

(891, 7) (891,)


In [23]:
x.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  22.0      1      0   7.2500         2
1       1    0  38.0      1      0  71.2833         0
2       3    0  26.0      0      0   7.9250         2
3       1    0  35.0      1      0  53.1000         2
4       3    1  35.0      0      0   8.0500         2

In [24]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(668, 7)
(223, 7)
(668,)
(223,)


In [27]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [28]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

Model fitting is a measure of how well a machine learning model generalizes to similar data to that on which it was trained.</br> A model that is well-fitted produces more accurate outcomes.</br> A model that is overfitted matches the data too closely.</br> A model that is underfitted doesn't match closely enough.

In [29]:
def model_insights(model):
  m = model.fit(x_train,y_train)
  ypred = m.predict(x_test)
  print('Confusion Matrix\n',confusion_matrix(y_test,ypred))
  print('Accuracy Score\n',accuracy_score(y_test,ypred)) #Tests accuracy
  print('Classification Report\n',classification_report(y_test,ypred))

# KNN

In [36]:
m1 = KNeighborsClassifier(n_neighbors=21)
model_insights(m1)

Confusion Matrix
 [[116  16]
 [ 55  36]]
Accuracy Score
 0.6816143497757847
Classification Report
               precision    recall  f1-score   support

           0       0.68      0.88      0.77       132
           1       0.69      0.40      0.50        91

    accuracy                           0.68       223
   macro avg       0.69      0.64      0.63       223
weighted avg       0.68      0.68      0.66       223



# LogRegg

In [37]:
m2 = LogisticRegression()
model_insights(m2)

Confusion Matrix
 [[114  18]
 [ 35  56]]
Accuracy Score
 0.7623318385650224
Classification Report
               precision    recall  f1-score   support

           0       0.77      0.86      0.81       132
           1       0.76      0.62      0.68        91

    accuracy                           0.76       223
   macro avg       0.76      0.74      0.75       223
weighted avg       0.76      0.76      0.76       223



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


# Decision Tree

In [38]:
m3 = DecisionTreeClassifier(criterion = 'gini',max_depth = 12)
model_insights(m3)

Confusion Matrix
 [[117  15]
 [ 36  55]]
Accuracy Score
 0.7713004484304933
Classification Report
               precision    recall  f1-score   support

           0       0.76      0.89      0.82       132
           1       0.79      0.60      0.68        91

    accuracy                           0.77       223
   macro avg       0.78      0.75      0.75       223
weighted avg       0.77      0.77      0.76       223



# SVM

In [39]:
m4 = SVC(kernel = 'linear',C = 1.0)
model_insights(m4)

Confusion Matrix
 [[111  21]
 [ 32  59]]
Accuracy Score
 0.7623318385650224
Classification Report
               precision    recall  f1-score   support

           0       0.78      0.84      0.81       132
           1       0.74      0.65      0.69        91

    accuracy                           0.76       223
   macro avg       0.76      0.74      0.75       223
weighted avg       0.76      0.76      0.76       223



# Random Forest Classifier

In [40]:
m5 = RandomForestClassifier(n_estimators=30,criterion='gini',max_depth=10)
model_insights(m5)

Confusion Matrix
 [[119  13]
 [ 34  57]]
Accuracy Score
 0.7892376681614349
Classification Report
               precision    recall  f1-score   support

           0       0.78      0.90      0.84       132
           1       0.81      0.63      0.71        91

    accuracy                           0.79       223
   macro avg       0.80      0.76      0.77       223
weighted avg       0.79      0.79      0.78       223



# Model 2
Columns excluded - PassengerID, Name, Ticket,Cabin, Sex

In [41]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [42]:
x = df.iloc[:,[2,5,6,7,9,11]]
y = df.iloc[:,1]
print(x.shape,y.shape)

(891, 6) (891,)


In [45]:
df.corr()['Survived']

PassengerId   -0.005007
Survived       1.000000
Pclass        -0.338481
Sex           -0.543351
Age           -0.069809
SibSp         -0.035322
Parch          0.081629
Fare           0.257307
Embarked      -0.167675
Name: Survived, dtype: float64

In [46]:
x.head()

Pclass   Age  SibSp  Parch     Fare  Embarked
0       3  22.0      1      0   7.2500         2
1       1  38.0      1      0  71.2833         0
2       3  26.0      0      0   7.9250         2
3       1  35.0      1      0  53.1000         2
4       3  35.0      0      0   8.0500         2

In [47]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [48]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(668, 6)
(223, 6)
(668,)
(223,)


## **KNN**

In [53]:
m1 = KNeighborsClassifier(n_neighbors=29)
model_insights(m1)

Confusion Matrix
 [[109  19]
 [ 52  43]]
Accuracy Score
 0.6816143497757847
Classification Report
               precision    recall  f1-score   support

           0       0.68      0.85      0.75       128
           1       0.69      0.45      0.55        95

    accuracy                           0.68       223
   macro avg       0.69      0.65      0.65       223
weighted avg       0.68      0.68      0.67       223



## **LogRegg**

In [54]:
m2 = LogisticRegression()
model_insights(m2)

Confusion Matrix
 [[109  19]
 [ 52  43]]
Accuracy Score
 0.6816143497757847
Classification Report
               precision    recall  f1-score   support

           0       0.68      0.85      0.75       128
           1       0.69      0.45      0.55        95

    accuracy                           0.68       223
   macro avg       0.69      0.65      0.65       223
weighted avg       0.68      0.68      0.67       223



## **Decision Tree**

In [62]:
m3 = DecisionTreeClassifier(criterion = 'gini', max_depth = 9)
model_insights(m3)

Confusion Matrix
 [[98 30]
 [43 52]]
Accuracy Score
 0.672645739910314
Classification Report
               precision    recall  f1-score   support

           0       0.70      0.77      0.73       128
           1       0.63      0.55      0.59        95

    accuracy                           0.67       223
   macro avg       0.66      0.66      0.66       223
weighted avg       0.67      0.67      0.67       223



## **SVM**

In [63]:
m4 = SVC(kernel='linear',C=1.0)
model_insights(m4)

Confusion Matrix
 [[105  23]
 [ 52  43]]
Accuracy Score
 0.6636771300448431
Classification Report
               precision    recall  f1-score   support

           0       0.67      0.82      0.74       128
           1       0.65      0.45      0.53        95

    accuracy                           0.66       223
   macro avg       0.66      0.64      0.64       223
weighted avg       0.66      0.66      0.65       223



## **Random Forest Classifier**

In [64]:
m5 = RandomForestClassifier(n_estimators=30,criterion='gini',max_depth=8)
model_insights(m5)

Confusion Matrix
 [[106  22]
 [ 37  58]]
Accuracy Score
 0.7354260089686099
Classification Report
               precision    recall  f1-score   support

           0       0.74      0.83      0.78       128
           1       0.72      0.61      0.66        95

    accuracy                           0.74       223
   macro avg       0.73      0.72      0.72       223
weighted avg       0.73      0.74      0.73       223

