In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [111]:
df = pd.read_csv('adult (1).csv',header = None)
df.head()

0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10  11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174   0  40   
1     Exec-managerial         Husband   White     Male     0   0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0   0  40   
3   Handlers-cleaners         Husband   Black     Male     0   0  40   
4      Prof-specialty            Wife   Black   Female     0   0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

In [112]:
df.shape

(32561, 15)

In [113]:
df.columns = ['Age','Workclass','Fnlwgt','Education','Education_num','Marital_status','Occupation','Relationship',
              'Race','Sex','Capital_gain','Capital_loss','Hours_per_week','Native_country','Income']
df.head()

Age          Workclass  Fnlwgt   Education  Education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        Marital_status          Occupation    Relationship    Race      Sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   Capital_gain  Capital_loss  Hours_per_week  Native_country  Income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [114]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
Education_num     0
Marital_status    0
Occupation        0
Relationship      0
Race              0
Sex               0
Capital_gain      0
Capital_loss      0
Hours_per_week    0
Native_country    0
Income            0
dtype: int64

In [115]:
df.dtypes

Age                int64
Workclass         object
Fnlwgt             int64
Education         object
Education_num      int64
Marital_status    object
Occupation        object
Relationship      object
Race              object
Sex               object
Capital_gain       int64
Capital_loss       int64
Hours_per_week     int64
Native_country    object
Income            object
dtype: object

In [116]:
print(df['Workclass'].unique())
print(df['Education'].unique())
print(df['Marital_status'].unique())
print(df['Occupation'].unique())
print(df['Relationship'].unique())
print(df['Race'].unique())
print(df['Sex'].unique())
print(df['Native_country'].unique())
print(df['Income'].unique())

[' State-gov' ' Self-emp-not-inc' ' Private' ' Federal-gov' ' Local-gov'
 ' ?' ' Self-emp-inc' ' Without-pay' ' Never-worked']
[' Bachelors' ' HS-grad' ' 11th' ' Masters' ' 9th' ' Some-college'
 ' Assoc-acdm' ' Assoc-voc' ' 7th-8th' ' Doctorate' ' Prof-school'
 ' 5th-6th' ' 10th' ' 1st-4th' ' Preschool' ' 12th']
[' Never-married' ' Married-civ-spouse' ' Divorced'
 ' Married-spouse-absent' ' Separated' ' Married-AF-spouse' ' Widowed']
[' Adm-clerical' ' Exec-managerial' ' Handlers-cleaners' ' Prof-specialty'
 ' Other-service' ' Sales' ' Craft-repair' ' Transport-moving'
 ' Farming-fishing' ' Machine-op-inspct' ' Tech-support' ' ?'
 ' Protective-serv' ' Armed-Forces' ' Priv-house-serv']
[' Not-in-family' ' Husband' ' Wife' ' Own-child' ' Unmarried'
 ' Other-relative']
[' White' ' Black' ' Asian-Pac-Islander' ' Amer-Indian-Eskimo' ' Other']
[' Male' ' Female']
[' United-States' ' Cuba' ' Jamaica' ' India' ' ?' ' Mexico' ' South'
 ' Puerto-Rico' ' Honduras' ' England' ' Canada' ' Germany' 

In [117]:
df['Workclass'].value_counts()

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1298
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: Workclass, dtype: int64

In [118]:
df['Education'].value_counts()

 HS-grad         10501
 Some-college     7291
 Bachelors        5355
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: Education, dtype: int64

In [119]:
df['Marital_status'].value_counts()

 Married-civ-spouse       14976
 Never-married            10683
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: Marital_status, dtype: int64

In [120]:
df['Occupation'].value_counts()

 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3770
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 ?                    1843
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: Occupation, dtype: int64

In [121]:
df['Relationship'].value_counts()

 Husband           13193
 Not-in-family      8305
 Own-child          5068
 Unmarried          3446
 Wife               1568
 Other-relative      981
Name: Relationship, dtype: int64

In [122]:
df['Race'].value_counts()

 White                 27816
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
Name: Race, dtype: int64

In [123]:
df['Sex'].value_counts()

 Male      21790
 Female    10771
Name: Sex, dtype: int64

In [124]:
df['Native_country'].value_counts()

 United-States                 29170
 Mexico                          643
 ?                               583
 Philippines                     198
 Germany                         137
 Canada                          121
 Puerto-Rico                     114
 El-Salvador                     106
 India                           100
 Cuba                             95
 England                          90
 Jamaica                          81
 South                            80
 China                            75
 Italy                            73
 Dominican-Republic               70
 Vietnam                          67
 Guatemala                        64
 Japan                            62
 Poland                           60
 Columbia                         59
 Taiwan                           51
 Haiti                            44
 Iran                             43
 Portugal                         37
 Nicaragua                        34
 Peru                             31
 

In [125]:
df['Income'].value_counts()

 <=50K    24720
 >50K      7841
Name: Income, dtype: int64

In [126]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [127]:
df['Workclass'] = lb.fit_transform(df['Workclass'])
df['Education'] = lb.fit_transform(df['Education'])
df['Marital_status'] = lb.fit_transform(df['Marital_status'])
df['Occupation'] = lb.fit_transform(df['Occupation'])
df['Relationship'] = lb.fit_transform(df['Relationship'])
df['Race'] = lb.fit_transform(df['Race'])
df['Sex'] = lb.fit_transform(df['Sex'])
df['Native_country'] = lb.fit_transform(df['Native_country'])
df['Income'] = lb.fit_transform(df['Income'])

In [128]:
df.dtypes

Age               int64
Workclass         int64
Fnlwgt            int64
Education         int64
Education_num     int64
Marital_status    int64
Occupation        int64
Relationship      int64
Race              int64
Sex               int64
Capital_gain      int64
Capital_loss      int64
Hours_per_week    int64
Native_country    int64
Income            int64
dtype: object

In [129]:
df['Workclass'].value_counts().sort_values()

3        7
8       14
1      960
5     1116
7     1298
0     1836
2     2093
6     2541
4    22696
Name: Workclass, dtype: int64

In [130]:
df['Workclass'].unique()

array([7, 6, 4, 1, 2, 0, 5, 8, 3])

In [131]:
df['Education'].value_counts().sort_values()

13       51
3       168
4       333
10      413
2       433
6       514
14      576
5       646
0       933
7      1067
1      1175
8      1382
12     1723
9      5355
15     7291
11    10501
Name: Education, dtype: int64

In [132]:
df['Education'].unique()

array([ 9, 11,  1, 12,  6, 15,  7,  8,  5, 10, 14,  4,  0,  3, 13,  2])

In [133]:
df['Marital_status'].value_counts().sort_values()

1       23
3      418
6      993
5     1025
0     4443
4    10683
2    14976
Name: Marital_status, dtype: int64

In [134]:
df['Marital_status'].unique()

array([4, 2, 0, 3, 5, 1, 6])

In [135]:
df['Occupation'].value_counts().sort_values()

2        9
9      149
11     649
13     928
5      994
6     1370
14    1597
0     1843
7     2002
8     3295
12    3650
1     3770
4     4066
3     4099
10    4140
Name: Occupation, dtype: int64

In [136]:
df['Occupation'].unique()

array([ 1,  4,  6, 10,  8, 12,  3, 14,  5,  7, 13,  0, 11,  2,  9])

In [137]:
df['Relationship'].value_counts().sort_values()

2      981
5     1568
4     3446
3     5068
1     8305
0    13193
Name: Relationship, dtype: int64

In [138]:
df['Relationship'].unique()

array([1, 0, 5, 3, 4, 2])

In [139]:
df['Race'].value_counts().sort_values()

3      271
0      311
1     1039
2     3124
4    27816
Name: Race, dtype: int64

In [140]:
df['Race'].unique()

array([4, 2, 1, 0, 3])

In [141]:
df['Sex'].value_counts().sort_values()

0    10771
1    21790
Name: Sex, dtype: int64

In [142]:
df['Sex'].unique()

array([1, 0])

In [143]:
df['Native_country'].value_counts().sort_values()

15        1
34       12
16       13
18       13
28       14
41       16
37       18
25       18
38       19
1        19
17       20
21       24
7        28
12       29
10       29
29       31
27       34
32       37
20       43
14       44
36       51
4        59
31       60
24       62
13       64
40       67
6        70
22       73
3        75
35       80
23       81
9        90
5        95
19      100
8       106
33      114
2       121
11      137
30      198
0       583
26      643
39    29170
Name: Native_country, dtype: int64

In [144]:
df['Native_country'].unique()

array([39,  5, 23, 19,  0, 26, 35, 33, 16,  9,  2, 11, 20, 30, 22, 31,  4,
        1, 37,  7, 25, 36, 14, 32,  6,  8, 10, 13,  3, 24, 41, 29, 28, 34,
       38, 12, 27, 40, 17, 21, 18, 15])

In [145]:
df['Income'].value_counts().sort_values()

1     7841
0    24720
Name: Income, dtype: int64

In [146]:
df['Income'].unique()

array([0, 1])

In [147]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)

(32561, 14)
(32561,)


In [148]:
x.head()

Age  Workclass  Fnlwgt  Education  Education_num  Marital_status  \
0   39          7   77516          9             13               4   
1   50          6   83311          9             13               2   
2   38          4  215646         11              9               0   
3   53          4  234721          1              7               2   
4   28          4  338409          9             13               2   

   Occupation  Relationship  Race  Sex  Capital_gain  Capital_loss  \
0           1             1     4    1          2174             0   
1           4             0     4    1             0             0   
2           6             1     4    1             0             0   
3           6             0     2    1             0             0   
4          10             5     2    0             0             0   

   Hours_per_week  Native_country  
0              40              39  
1              13              39  
2              40              39  
3              40              39  
4              40               5

In [165]:
y.head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    1
8    1
9    1
Name: Income, dtype: int64

In [150]:
from sklearn.model_selection import train_test_split

In [151]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25, train_size = 0.75)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24420, 14)
(8141, 14)
(24420,)
(8141,)


In [152]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [153]:
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import accuracy_score

In [154]:
def apply_model(model,x_train,y_train,x_test,y_test):
    m = model
    m.fit(x_train,y_train)
    print('Training score',m.score(x_train,y_train))
    print('Testing score',m.score(x_test,y_test))
    ypred = m.predict(x_test)
    print('y_pred\n',ypred)
    cm = confusion_matrix(y_test,ypred)
    print('Confusion Matrix\n',cm)
    print('Accuracy_Score',accuracy_score(y_test,ypred))
    print('Classification Report\n',classification_report(y_test,ypred))

Gaussian Naive Bayes Classifier

In [155]:
from sklearn.naive_bayes import GaussianNB
from sklearn.gaussian_process import GaussianProcessClassifier

In [156]:
clf = GaussianNB()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
accuracy_score(y_test, y_pred, normalize = True)
print('Confusion Matrix\n',confusion_matrix(y_test,y_pred))
print('Accuracy_Score',accuracy_score(y_test,y_pred))  
print('Classification Report\n',classification_report(y_test,y_pred))

Confusion Matrix
 [[5826  306]
 [1430  579]]
Accuracy_Score 0.7867583834909716
Classification Report
               precision    recall  f1-score   support

           0       0.80      0.95      0.87      6132
           1       0.65      0.29      0.40      2009

    accuracy                           0.79      8141
   macro avg       0.73      0.62      0.64      8141
weighted avg       0.77      0.79      0.75      8141



Decision Tree Classifier

In [157]:
m2 = DecisionTreeClassifier(criterion = 'gini', max_depth = 9)
apply_model(m2,x_train,y_train,x_test,y_test)

Training score 0.8666257166257166
Testing score 0.8508782704827417
y_pred
 [0 0 0 ... 0 0 0]
Confusion Matrix
 [[5868  264]
 [ 950 1059]]
Accuracy_Score 0.8508782704827417
Classification Report
               precision    recall  f1-score   support

           0       0.86      0.96      0.91      6132
           1       0.80      0.53      0.64      2009

    accuracy                           0.85      8141
   macro avg       0.83      0.74      0.77      8141
weighted avg       0.85      0.85      0.84      8141



In [158]:
ypred_dt = m2.predict(x_test)
print(ypred_dt)

[0 0 0 ... 0 0 0]


Random Forest Classifier

In [159]:
m3 = RandomForestClassifier(n_estimators = 25, criterion = 'gini', max_depth = 11)
apply_model(m3,x_train,y_train,x_test,y_test)

Training score 0.8765356265356266
Testing score 0.8589853826311264
y_pred
 [0 0 0 ... 0 0 0]
Confusion Matrix
 [[5859  273]
 [ 875 1134]]
Accuracy_Score 0.8589853826311264
Classification Report
               precision    recall  f1-score   support

           0       0.87      0.96      0.91      6132
           1       0.81      0.56      0.66      2009

    accuracy                           0.86      8141
   macro avg       0.84      0.76      0.79      8141
weighted avg       0.85      0.86      0.85      8141



In [160]:
ypred_rf = m3.predict(x_test)
print(ypred_rf)

[0 0 0 ... 0 0 0]


Logistic Regression

In [161]:
m4 = LogisticRegression(solver = 'liblinear')
apply_model(m4,x_train,y_train,x_test,y_test)

Training score 0.7927108927108927
Testing score 0.7797567866355485
y_pred
 [0 0 0 ... 0 0 0]
Confusion Matrix
 [[5795  337]
 [1456  553]]
Accuracy_Score 0.7797567866355485
Classification Report
               precision    recall  f1-score   support

           0       0.80      0.95      0.87      6132
           1       0.62      0.28      0.38      2009

    accuracy                           0.78      8141
   macro avg       0.71      0.61      0.62      8141
weighted avg       0.76      0.78      0.75      8141



In [162]:
ypred_logreg = m4.predict(x_test)
print(ypred_logreg)

[0 0 0 ... 0 0 0]


KNN Classifier

In [163]:
m5 = KNeighborsClassifier(n_neighbors=29)
apply_model(m5,x_train,y_train,x_test,y_test)

Training score 0.803931203931204
Testing score 0.7929001351185359
y_pred
 [0 0 0 ... 0 0 0]
Confusion Matrix
 [[6083   49]
 [1637  372]]
Accuracy_Score 0.7929001351185359
Classification Report
               precision    recall  f1-score   support

           0       0.79      0.99      0.88      6132
           1       0.88      0.19      0.31      2009

    accuracy                           0.79      8141
   macro avg       0.84      0.59      0.59      8141
weighted avg       0.81      0.79      0.74      8141



In [164]:
ypred_knn = m5.predict(x_test)
print(ypred_knn)

[0 0 0 ... 0 0 0]
